import argparse
import torch
import os
import time
import configparser
from dataset_traffic import get_dataloader
from main_model import LOFTTraffic
from utils import train, evaluate, set_seed
import logging
import sys
import re
import glob
import warnings

parser = argparse.ArgumentParser(description="LOFT Time Series Imputation")

parser.add_argument("--config", type=str, default="config/PEMS04.conf")
parser.add_argument("--dataset", type=str, default=None)
parser.add_argument("--miss_type", type=str, default=None)
parser.add_argument('--miss_rate', type=str, default=None)
parser.add_argument('--device', default=None)
parser.add_argument('--mode', type=str, default='train', choices=['train', 'eval'], help='train or eval')
parser.add_argument("--seed", type=int, default=127)
parser.add_argument("--warmup_epochs", type=int, default=None, help="Pure flow-matching warm-up epochs before rectification")
parser.add_argument("--epoch_offset", type=int, default=0, help="Epoch offset used for resumed rectification scheduling")

parser.add_argument("--initial_lr", type=float, default=None)
parser.add_argument("--final_lr", type=float, default=None)
parser.add_argument("--rectification_lr", type=float, default=None)
parser.add_argument("--high_lr_epochs", type=int, default=None)

parser.add_argument("--savename", type=str, default="")
parser.add_argument("--results_file", type=str, default=None)
parser.add_argument("--output_root", type=str, default=".", help="Root directory for params/results generated by this run")
parser.add_argument("--data_prefix", type=str, default=None, help="Override config file data_prefix")
parser.add_argument("--trace_file", type=str, default=None, help="Optional path to save inference trajectories and velocities for plotting")
parser.add_argument("--trace_batches", type=int, default=1, help="Number of eval batches to save traces for")
parser.add_argument("--trace_samples", type=int, default=1, help="Number of stochastic samples per batch to save traces for")
parser.add_argument("--cond_path", type=str, default=None, help="Optional trained LOFT weight for eval/resume")
parser.add_argument("--low_rank_prior_path", type=str, default=None, help="Low-rank prior npz containing prior_mean and prior_uncertainty")
parser.add_argument("--imputed_datapath", type=str, default=None, help="Legacy alias for --low_rank_prior_path")
parser.add_argument("--logfile", type=str, default="")

parser.add_argument(
    "--targetstrategy", type=str, default="mix", choices=["mix", "random", "historical"]
)

parser.add_argument("--num_steps", type=int, default=None, help="Override num_steps in config")
parser.add_argument("--inference_steps", type=int, default=None, help="Override inference_steps in config")
parser.add_argument("--layers", type=int, default=None, help="Override model layers in config")
parser.add_argument("--epochs", type=int, default=None, help="Override epochs in config")
parser.add_argument("--min_alpha", type=float, default=None)
parser.add_argument("--exp_for_hard", type=float, default=None)
parser.add_argument("--exp_for_easy", type=float, default=None)
parser.add_argument("--node_start", type=int, default=0, help="Inclusive start node index")
parser.add_argument("--node_end", type=int, default=307, help="Exclusive end node index")

parser.add_argument("--use_consistency", type=int, default=1, choices=[0, 1], help="是否开启终点一致性损失")
parser.add_argument("--finetune", type=int, default=0, choices=[0, 1], help="Legacy flag; use --cond_path to load a checkpoint")

args = parser.parse_args()

set_seed(args.seed)


def get_cond_epoch_tag(cond_path):
    if not cond_path:
        return "from_no_pretrain"
    basename = os.path.basename(cond_path)
    match = re.search(r"(?:^|_)epoch(\d+)(?:_|\.|$)", basename)
    if match is None:
        match = re.search(r"(?:^|_)ep(\d+)(?:_|\.|$)", basename)
    if match:
        return f"from_epoch{match.group(1)}"
    return "from_unknown_epoch"


def resolve_device(requested_device):

    try:
        device = torch.device(requested_device)
    except (TypeError, RuntimeError) as exc:
        raise ValueError(f"Invalid --device value: {requested_device!r}") from exc

    if device.type != "cuda":
        return str(device)

    cuda_warnings = []
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        cuda_available = torch.cuda.is_available()
        device_count = torch.cuda.device_count() if cuda_available else 0
    cuda_warnings = [str(item.message) for item in caught]

    if not cuda_available:
        details = [
            f"Requested CUDA device {requested_device!r}, but PyTorch cannot use CUDA.",
            f"torch={torch.__version__}, torch.version.cuda={torch.version.cuda}",
        ]
        if cuda_warnings:
            details.append("CUDA init warning: " + " | ".join(cuda_warnings))
        details.extend(
            [
                "Please check `nvidia-smi` and make sure the NVIDIA driver is running.",
                "If the driver is older than this PyTorch CUDA build, either update the driver or use a PyTorch build compiled for the installed driver.",
                "For a CPU-only smoke test, pass `--device cpu`.",
            ]
        )
        raise RuntimeError("\n".join(details))

    requested_index = device.index if device.index is not None else 0
    if requested_index >= device_count:
        raise RuntimeError(
            f"Requested {requested_device!r}, but PyTorch sees only {device_count} CUDA device(s). "
            f"Use a device index in [0, {device_count - 1}] or set CUDA_VISIBLE_DEVICES appropriately."
        )

    return str(device)


if args.dataset:
    dataset_name = args.dataset
    args.config = f"config/{dataset_name}.conf"
else:
    dataset_name = os.path.splitext(os.path.basename(args.config))[0]

current_time_str = time.strftime("%Y%m%d_%H%M%S")
cond_epoch_tag = get_cond_epoch_tag(args.cond_path) if args.cond_path else "warmup_rectified"

if not args.logfile:
    main_log_dir = "./logs/main"
    if not os.path.exists(main_log_dir):
        os.makedirs(main_log_dir)
    args.logfile = os.path.join(
        main_log_dir,
        f"log_{dataset_name}_{cond_epoch_tag}_{current_time_str}.log",
    )

log_dir = os.path.dirname(args.logfile)
if log_dir and not os.path.exists(log_dir):
    os.makedirs(log_dir)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[
        logging.FileHandler(args.logfile, mode='a'),
        logging.StreamHandler(sys.stdout)
    ],
    force=True
)

config = configparser.ConfigParser()
config.read(args.config)

if args.initial_lr is not None:
    config["train"]["initial_lr"] = str(args.initial_lr)

if args.final_lr is not None:
    config["train"]["final_lr"] = str(args.final_lr)

if args.rectification_lr is not None:
    config["train"]["rectification_lr"] = str(args.rectification_lr)

if args.high_lr_epochs is not None:
    config["train"]["high_lr_epochs"] = str(args.high_lr_epochs)
if args.warmup_epochs is not None:
    config["train"]["warmup_epochs"] = str(args.warmup_epochs)
config["train"]["epoch_offset"] = str(args.epoch_offset)

if args.miss_type is not None:
    config["train"]["type"] = args.miss_type
if args.miss_rate is not None:
    config["train"]["miss_rate"] = args.miss_rate

config["model"]["target_strategy"] = args.targetstrategy

if "train" not in config: config["train"] = {}
config["train"]["use_consistency"] = str(args.use_consistency)

if args.num_steps is not None:
    config["flow_matching"]["num_steps"] = str(args.num_steps)
if args.inference_steps is not None:
    config["flow_matching"]["inference_steps"] = str(args.inference_steps)
if args.layers is not None:
    config["flow_matching"]["layers"] = str(args.layers)
if args.epochs is not None:
    config["train"]["epochs"] = str(args.epochs)

warmup_epochs = int(config["train"].get("warmup_epochs", 0))
rectification_epochs = int(config["train"]["epochs"])
total_epochs = warmup_epochs + rectification_epochs
config["train"]["total_epochs"] = str(total_epochs)

if args.min_alpha is not None:
    config["flow_matching"]["min_alpha"] = str(args.min_alpha)

if args.exp_for_hard is not None:
    config["flow_matching"]["exp_for_hard"] = str(args.exp_for_hard)

if args.exp_for_easy is not None:
    config["flow_matching"]["exp_for_easy"] = str(args.exp_for_easy)

if args.device is not None:
    config["model"]["device"] = args.device
else:
    if "model" in config and "device" in config["model"]:
        args.device = config["model"]["device"]
    else:
        args.device = "cuda:6"
        if "model" not in config: config["model"] = {}
        config["model"]["device"] = args.device

if args.mode == "eval" and not args.cond_path:
    raise ValueError(
        "Inference/eval mode requires --cond_path, otherwise the model would use random weights. "
        "Example: python run.py --mode eval --cond_path params/PEMS04_SC-TC_0.8_from_epoch145_20260528_202319_cond_ep6.pth"
    )

args.device = resolve_device(args.device)
config["model"]["device"] = args.device

miss_type = config['train']['type']
miss_rate = config['train']['miss_rate']

if not os.path.isabs(args.output_root):
    args.output_root = os.path.join(os.path.dirname(os.path.abspath(__file__)), args.output_root)
os.makedirs(args.output_root, exist_ok=True)

if not args.results_file:
    results_dir = os.path.join(args.output_root, "results")
    os.makedirs(results_dir, exist_ok=True)
    args.results_file = os.path.join(
        results_dir,
        f"results_{dataset_name}_{cond_epoch_tag}_{current_time_str}.csv",
    )

if not args.savename:
    args.savename = f"{dataset_name}_{miss_type}_{miss_rate}_{cond_epoch_tag}_{current_time_str}"

base_name = f"{dataset_name}_{miss_type}_{miss_rate}"
savename_to_use = args.savename
results_file_to_use = args.results_file

logging.info("=" * 50)
logging.info(f"mode: {args.mode}")
logging.info(f"dataset_name: {dataset_name}")
logging.info(f"miss_type: {miss_type}")
logging.info(f"miss_rate: {miss_rate}")
logging.info(f"use_consistency: {config['train']['use_consistency']}")
logging.info(f"warmup_epochs: {config['train'].get('warmup_epochs', 0)}")
logging.info(f"rectification_epochs: {config['train']['epochs']}")
logging.info(f"total_epochs: {config['train']['total_epochs']}")
logging.info(f"savename: {savename_to_use}")
logging.info(f"results_file: {results_file_to_use}")
logging.info(f"output_root: {args.output_root}")
logging.info(f"device: {args.device}")
logging.info(f"seed: {args.seed}")
logging.info(f"initial_lr: {config['train']['initial_lr']}")
logging.info(f"final_lr: {config['train']['final_lr']}")
logging.info(f"rectification_lr: {config['train'].get('rectification_lr', config['train']['final_lr'])}")
logging.info(f"high_lr_epochs: {config['train']['high_lr_epochs']}")
logging.info(f"layers: {config['flow_matching']['layers']}")
logging.info(f"min alpha: {config['flow_matching']['min_alpha']}")
logging.info(f"node range: [{args.node_start}, {args.node_end})")

use_nni = int(config['train']['use_nni'])

data_prefix = config['file']['data_prefix']
if args.data_prefix is not None:
    data_prefix = args.data_prefix
if not os.path.isabs(data_prefix):
    data_prefix = os.path.join(os.path.dirname(os.path.abspath(__file__)), data_prefix)

val_ratio = float(config['train']['val_ratio'])
test_ratio = float(config['train']['test_ratio'])
sample_len = int(config['train']['sample_len'])
batch_size = int(config['train']['batch_size'])
nsample = int(config['flow_matching']['nsample'])

true_datapath = os.path.join(data_prefix, f"true_data_{miss_type}_{miss_rate}_v2.npz")
miss_datapath = os.path.join(data_prefix, f"miss_data_{miss_type}_{miss_rate}_v2.npz")

low_rank_prior_dir = config['file'].get('low_rank_prior_dir', config['file'].get('imputed_data_dir', 'data/pre_impute'))
if not os.path.isabs(low_rank_prior_dir):
    low_rank_prior_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), low_rank_prior_dir)

low_rank_prior_path = args.low_rank_prior_path or args.imputed_datapath
if low_rank_prior_path is None:
    exact_candidates = [
        os.path.join(low_rank_prior_dir, f"prior_{dataset_name}_{miss_type}_{miss_rate}.npz"),
        os.path.join(low_rank_prior_dir, f"imputed_{dataset_name}_{miss_type}_{miss_rate}.npz"),
    ]
    timestamped_candidates = sorted(
        glob.glob(os.path.join(low_rank_prior_dir, f"prior_{dataset_name}_{miss_type}_{miss_rate}_*.npz"))
        + glob.glob(os.path.join(low_rank_prior_dir, f"imputed_{dataset_name}_{miss_type}_{miss_rate}_*.npz")),
        reverse=True,
    )
    candidates = exact_candidates + timestamped_candidates
    low_rank_prior_path = next((path for path in candidates if os.path.exists(path)), candidates[-1])
if not os.path.isabs(low_rank_prior_path):
    low_rank_prior_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), low_rank_prior_path)
logging.info(f"data_prefix: {data_prefix}")
logging.info(f"true_datapath: {true_datapath}")
logging.info(f"miss_datapath: {miss_datapath}")
logging.info(f"low_rank_prior_path: {low_rank_prior_path}")
logging.info(f"batch_size: {batch_size}")
logging.info(f"sample_len: {sample_len}")
logging.info(f"val_ratio: {val_ratio}")
logging.info(f"test_ratio: {test_ratio}")
logging.info(f"num_steps: {config['flow_matching']['num_steps']}")
logging.info(f"inference_steps: {config['flow_matching']['inference_steps']}")
logging.info(f"nsample: {nsample}")
logging.info(f"channels: {config['flow_matching']['channels']}")
logging.info(f"nheads: {config['flow_matching']['nheads']}")
logging.info(f"use_nni: {use_nni}")

train_loader, valid_loader, test_loader, target_dim, _std, _mean = get_dataloader(
    true_datapath,
    miss_datapath,
    low_rank_prior_path,
    val_ratio,
    test_ratio,
    batch_size,
    sample_len,
    node_start=args.node_start,
    node_end=args.node_end,
)
logging.info(f"target_dim: {target_dim}")
logging.info(f"train_batches: {len(train_loader)}")
logging.info(f"valid_batches: {len(valid_loader)}")
logging.info(f"test_batches: {len(test_loader)}")
logging.info(f"normalization_std: {_std}")
logging.info(f"normalization_mean: {_mean}")
model = LOFTTraffic(config, target_dim, args.device).to(args.device)


def run_configured_evaluation(model, test_loader, std, mean, use_nni, nsample, results_file, base_savename):
    steps = int(model.config["flow_matching"].get("inference_steps", 2))
    logging.info("\n" + "=" * 50)
    logging.info(f"[Final Evaluation] Running {steps}-step inference.")
    logging.info("=" * 50)

    model.config["flow_matching"]["inference_steps"] = str(steps)

    tensor_save_name = f"evaluation_tensors_{base_savename}_NFE{steps}.pth"
    tensor_save_path = os.path.join(args.output_root, "results", tensor_save_name)
    trace_file = args.trace_file
    if trace_file and not os.path.isabs(trace_file):
        trace_file = os.path.join(args.output_root, trace_file)

    evaluate(
        model,
        test_loader,
        std, mean, use_nni,
        nsample=nsample,
        results_file=results_file,
        tensor_save_path=tensor_save_path,
        trace_file=trace_file,
        trace_batches=args.trace_batches,
        trace_samples=args.trace_samples,
    )


if args.mode == 'train':

    if args.cond_path:
        if not os.path.isabs(args.cond_path):
            args.cond_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), args.cond_path)
        logging.info(f"Loading checkpoint from {args.cond_path} before LOFT training...")
        state_dict = torch.load(args.cond_path, map_location=args.device)
        model.velocity_net.load_state_dict(state_dict)

    train(
        model,
        config["train"],
        train_loader,
        valid_loader=valid_loader,
        test_loader=test_loader,
        _std=_std,
        _mean=_mean,
        savename=savename_to_use,
        output_root=args.output_root
    )

    run_configured_evaluation(model, test_loader, _std, _mean, use_nni, nsample, results_file_to_use, savename_to_use)

elif args.mode == 'eval':

    if not args.cond_path:
        raise ValueError("Evaluation requires --cond_path; otherwise the model would use random weights.")
    if not os.path.isabs(args.cond_path):
        args.cond_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), args.cond_path)
    logging.info(f"Loading checkpoint from {args.cond_path} for evaluation...")
    model.velocity_net.load_state_dict(torch.load(args.cond_path, map_location=args.device))

    model.eval()

    run_configured_evaluation(model, test_loader, _std, _mean, use_nni, nsample, results_file_to_use, savename_to_use)
