[generator]
graph_signal_matrix_filename = /data/maodawei/USTIN/data/PEMS07/PEMS07.npz
distancePath = /data/maodawei/USTIN/data/PEMS07/PEMS07.csv
save_filesdir = /data/maodawei/USTIN/data/miss_data/PEMS07/