[generator]
graph_signal_matrix_filename = /data/maodawei/USTIN/imputation_benchmark-main/GenerateData/PEMS03/PEMS03.npz
distancePath = /data/maodawei/USTIN/imputation_benchmark-main/GenerateData/PEMS03/PEMS03.csv
id_filename = /data/maodawei/USTIN/imputation_benchmark-main/GenerateData/PEMS03/PEMS03.txt
save_filesdir = /data/maodawei/USTIN/imputation_benchmark-main/GenerateData/generated_missing/PEMS03/
