[generator]
graph_signal_matrix_filename = /data/maodawei/USTIN/imputation_benchmark-main/GenerateData/PEMS04/PEMS04.npz
distancePath = /data/maodawei/USTIN/imputation_benchmark-main/GenerateData/PEMS04/PEMS04.csv
save_filesdir = /data/maodawei/USTIN/imputation_benchmark-main/GenerateData/generated_missing/PEMS04/
