[file]
data_prefix = data/miss_data/PEMS04
low_rank_prior_dir = data/pre_impute
imputed_data_dir = data/pre_impute
[train]
miss_rate = 0.8
type = SC-TC
warmup_epochs = 145
epochs = 6
batch_size = 32
use_nni = 0

test_ratio = 0.2
val_ratio = 0.2
sample_len = 12
initial_lr = 1e-3
final_lr = 5e-4
high_lr_epochs = 80
rectification_lr = 5e-5

[flow_matching]
layers = 2
channels = 64
nheads = 8
intg_time_embedding_dim = 64
num_steps = 10
inference_steps = 2
nsample = 10
min_alpha = 0.2
exp_for_hard = 0.05
exp_for_easy = 4.0

[model]
timeemb = 128
featureemb = 16
target_strategy = mix
device = cuda:7
