[file]
data_prefix = ./data/miss_data/PEMS04
imputed_data_dir = ./data/pre_impute
[train]
miss_rate = 0.8
type = SC-TC
epochs = 145
lr = 1e-3
batch_size = 32
use_nni = 0

test_ratio = 0.2
val_ratio = 0.2
sample_len = 12
alpha_warmup_ratio = 0.8
initial_lr = 1e-3
final_lr = 5e-4
high_lr_epochs = 80

[flow_matching]
layers = 4
channels = 64
nheads = 8
intg_time_embedding_dim = 64
num_steps = 20
inference_steps = 2
nsample = 10
min_alpha = 0.5
exp_for_hard = 0.05
exp_for_easy = 4.0

[model]
timeemb = 128
featureemb = 16
target_strategy = mix
device = cuda:0
